// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxl3HTqs3W5ZnbL5xlDLKdpPiePrmEZSA',
    appId: '1:897660277564:web:7a960aad44591d07fdc439',
    messagingSenderId: '897660277564',
    projectId: 'projeto-pedidos-472813',
    authDomain: 'projeto-pedidos-472813.firebaseapp.com',
    storageBucket: 'projeto-pedidos-472813.firebasestorage.app',
    measurementId: 'G-Z41RWR3C7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakh2LAmvLjYOBFmuEQ-waJnJGAQHb_wg',
    appId: '1:897660277564:android:8062c1d6fc739ab1fdc439',
    messagingSenderId: '897660277564',
    projectId: 'projeto-pedidos-472813',
    storageBucket: 'projeto-pedidos-472813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1sHFPNvtimpI6DlXObJuCB1syvD5JoNc',
    appId: '1:897660277564:ios:c1fb48b3371a76acfdc439',
    messagingSenderId: '897660277564',
    projectId: 'projeto-pedidos-472813',
    storageBucket: 'projeto-pedidos-472813.firebasestorage.app',
    iosBundleId: 'com.example.pedidoCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1sHFPNvtimpI6DlXObJuCB1syvD5JoNc',
    appId: '1:897660277564:ios:c1fb48b3371a76acfdc439',
    messagingSenderId: '897660277564',
    projectId: 'projeto-pedidos-472813',
    storageBucket: 'projeto-pedidos-472813.firebasestorage.app',
    iosBundleId: 'com.example.pedidoCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxl3HTqs3W5ZnbL5xlDLKdpPiePrmEZSA',
    appId: '1:897660277564:web:5872d13014dccbe5fdc439',
    messagingSenderId: '897660277564',
    projectId: 'projeto-pedidos-472813',
    authDomain: 'projeto-pedidos-472813.firebaseapp.com',
    storageBucket: 'projeto-pedidos-472813.firebasestorage.app',
    measurementId: 'G-7HE9L8YS2R',
  );

}