// lib/firebase_options_simula.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_NT-IAJnyIeN5RoMsdqYnz6tPitbOCMc',
    appId: '1:1099186542997:web:961c8ecf0ac55f75b4be9c',
    messagingSenderId: '1099186542997',
    projectId: 'projeto-pedidos-simula',
    authDomain: 'projeto-pedidos-simula.firebaseapp.com',
    // ✅ bucket correto:
    storageBucket: 'projeto-pedidos-simula.appspot.com',
    measurementId: 'G-YLRJ47SJ4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwxFYk1cG0H-Yb_4VtuPIF0mrBkGNqADU',
    appId: '1:1099186542997:android:59167a82f63dd5b3b4be9c',
    messagingSenderId: '1099186542997',
    projectId: 'projeto-pedidos-simula',
    // ✅ bucket correto:
    storageBucket: 'projeto-pedidos-simula.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cpwEDolmxe-yqzqq0Mq7J71ZW3Jgh64',
    appId: '1:1099186542997:ios:27722eb5142df5f0b4be9c',
    messagingSenderId: '1099186542997',
    projectId: 'projeto-pedidos-simula',
    // ✅ bucket correto:
    storageBucket: 'projeto-pedidos-simula.appspot.com',
    iosBundleId: 'com.example.pedidoCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2cpwEDolmxe-yqzqq0Mq7J71ZW3Jgh64',
    appId: '1:1099186542997:ios:27722eb5142df5f0b4be9c',
    messagingSenderId: '1099186542997',
    projectId: 'projeto-pedidos-simula',
    // ✅ bucket correto:
    storageBucket: 'projeto-pedidos-simula.appspot.com',
    iosBundleId: 'com.example.pedidoCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_NT-IAJnyIeN5RoMsdqYnz6tPitbOCMc',
    appId: '1:1099186542997:web:ac06b87a8cec7410b4be9c',
    messagingSenderId: '1099186542997',
    projectId: 'projeto-pedidos-simula',
    authDomain: 'projeto-pedidos-simula.firebaseapp.com',
    // ✅ bucket correto:
    storageBucket: 'projeto-pedidos-simula.appspot.com',
    measurementId: 'G-4467SB6X8J',
  );
}
